version: '3'

services:

  web:
    build:
      context: .
      args:
        USER_ID: $USER_ID
        GROUP_ID: $GROUP_ID
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: ./manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://procurement_portal:devpassword@db/procurement_portal
      - DJANGO_DEBUG=True
      - NODE_ENV=development
      - DJANGO_DEBUG_TOOLBAR
      - DJANGO_SECRET_KEY=not-secret-in-dev
      - DJANGO_WHITENOISE_AUTOREFRESH=True
      - TAG_MANAGER_ENABLED=False

  db:
    image: postgres:11.6
    environment:
      - POSTGRES_USER=procurement_portal
      - POSTGRES_PASSWORD=devpassword
      - POSTGRES_DB=procurement_portal
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
